/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    card: '#ffffff',
    border: '#e0e0e0',
    notification: '#ff3b30',
    primary: '#007AFF',
    secondary: '#666',
    accent: '#3a8cff',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    muted: '#f5f5f5',
    mutedForeground: '#999',
    destructive: '#FF3B30',
    score: '#FFA500',
    girlMode: '#E91E63',
    createPost: '#FF4444',
    location: '#3a8cff',
    surface: '#ffffff',
    surfaceVariant: '#f0f8ff',
    onSurface: '#000000',
    shadow: '#000',
    placeholder: '#8E8E93',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    card: '#1c1c1e',
    border: '#3c3c3e',
    notification: '#ff453a',
    primary: '#0A84FF',
    secondary: '#8e8e93',
    accent: '#64d2ff',
    success: '#30d158',
    warning: '#ff9f0a',
    error: '#ff453a',
    muted: '#2c2c2e',
    mutedForeground: '#8e8e93',
    destructive: '#ff453a',
    score: '#ff9f0a',
    girlMode: '#ff2d92',
    createPost: '#ff453a',
    location: '#64d2ff',
    surface: '#1c1c1e',
    surfaceVariant: '#2c2c2e',
    onSurface: '#ffffff',
    shadow: '#000',
    placeholder: '#8E8E93',
  },
};
